### ISSUE TITLE
binary

### ISSUE THREAD

**Issue by dalefrancis88** [crocksjs/crocks-extra#3]
### Description/Location

**location**: './helpers/binary.js'
**description**: `binary` takes a `func` of n-arity and forces it to be `binary`. It will allow you to enter any number of parameters but only the first two are respected

### Task List

* [ ] Check description with @evilsoft 
* [ ] Moved the main files
* [ ] Moved and updated the tests
* [ ] Moved and updated the documentation
* [ ] Marked the crocks version obsolete
* [ ] Updated the crocks documentation for obsolete status and pointed to new docs

For more information, see the `CONTRIBUTING` guide.

### Further info

Any further info that may be relevant...
