### ISSUE TITLE
fanout

### ISSUE THREAD

**Issue by dalefrancis88** [crocksjs/crocks-extra#6]
### Description/Location

**location:** './helpers/fanout.js'
**description:** a `Pair` is a product type monoid in crocks used to represent two distinct values. `fanout` is a `curry`'d function that takes two `functors` (`fst`, `snd`) and returns a `func` that takes a value that is then given to the `fst` and `snd` functions whose return values are used in constructing a `Pair`
[fanout](https://evilsoft.github.io/crocks/docs/functions/helpers.html#fanout)

### Task List

* [ ] Confirm with @evilsoft on the need to move and description
* [ ] Moved the main files
* [ ] Moved and updated the tests
* [ ] Moved and updated the documentation
* [ ] Marked the crocks version obsolete
* [ ] Updated the crocks documentation for obsolete status and pointed to new docs

For more information, see the `CONTRIBUTING` guide.

### Further info

Any further info that may be relevant...
