### ISSUE TITLE
liftA2, liftA3, liftN

### ISSUE THREAD

**Issue by dalefrancis88** [crocksjs/crocks-extra#8]
### Description/Location

**location:** './helpers/lift**.js'
**description:** These are helper functions to make working with applicatives nicer. I am thinking this **will not be moved**. However it is here to record that decision

### Task List

* [ ] Confirm move with @evilsoft 
* [ ] Moved the main files
* [ ] Moved and updated the tests
* [ ] Moved and updated the documentation
* [ ] Marked the crocks version obsolete
* [ ] Updated the crocks documentation for obsolete status and pointed to new docs

For more information, see the `CONTRIBUTING` guide.

### Further info

Any further info that may be relevant...
